### Exercice 1:

Write a function that takes a string, and two indexes (integers), and returns a slice of that string as well as the length of the string.
Call the function, and store the results in two variables

In [ ]:
#Write a function that takes a string, and two indexes (integers), and returns a slice of that string as well as the length of the string. Call the function, and store the results in two variables

def slice(string, i1, i2):
    if (i1<=i2):
        return (string[i1:i2],len(string))
    
        if(len(string)-1 < i2):
            i2=len(string)-1       
    else:
        i1, i2 = i2, i1
        return(slice(string,i1,i2))
    
   
string=input("string = ")
i1=int(input("i1 = "))
i2=int(input("i2 = "))
a,b=slice(string,i1,i2)
print("sliced_string = %s\nlength = %d" % (a,b))

### Exercice 2:

1. Write a function that takes two arguments, and returns the sum of the two.
2. Call the function with the values 1 and 2.1, then check the type of the result.
3. Call the function with the values False and 2, then check the type of the result.

In [2]:
def sum(a,b):
    return(a+b)

print(sum(1, 2.1))
print(type(sum(1, 2.1)))

print(sum(False, 2))
print(type(sum(False, 2)))

3.1
<class 'float'>
2
<class 'int'>


### Exercice 3:

Write a function that takes a string and returns a dictionary containing character frequency.

*example*

    string sample: 'test'
    
    expected result: {'t':2, 'e':1, 's':1}

In [ ]:
def char_frequency(string):
    Dict = {x: string.count(x) for x in string}
    return (Dict)

string = input("string = ") 
print(char_frequency(string))

### Exercice 4:

Given two lists, iterate both lists simultaniously, such the first list would display item in original order and the second list in reverse order

*example*:

In [3]:
#from lib import print_orl #this is a lib you dont have access to
#print_orl([1,2,3],[1,2,3])

1 3
2 2
3 1


In [4]:
def iterate_list(a,b):
    for i,j in zip(a, b[::-1]):
        print(i,j)
#The zip() function returns a zip object, which is an iterator of tuples where the first item in each passed iterator is paired together,
# and then the second item in each passed iterator are paired together etc.

a = [1, 2, 3]
b = [1, 2 ,3]
iterate_list(a,b)

1 3
2 2
3 1


### Exercice 5:

Given two 2d arrays, stack them horizontally.

*example:*

In [5]:
import numpy as np

#The input
a = np.ones((1, 10)).reshape(2, -1)
b = np.zeros((1, 10)).reshape(2, -1)

#Try to print input
print(f"a = {a}\n")
print(f"b = {b}\n")

#concatenate horizontally
o = np.hstack((a,b)) #hstack() function is used to stack the sequence of input arrays horizontally, to make a single array
print(f"output = {o}")

a = [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

b = [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

output = [[1. 1. 1. 1. 1. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 0. 0. 0. 0. 0.]]


### exercice 6:

Create the following patterns using the bellow arrays a and b, and numpy functions:

In [14]:
a = np.arange(3)
b = np.ones((3,3,3))


#output1 the following array: array([0, 0, 0, 1, 1, 1, 2, 2, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2])
def output1(a):
    v1 = np.repeat(a,3)
    v2 = np.hstack((a,a,a))
    o1 = np.hstack((v1,v2))
    return(o1)

print(f"output1 = {output1(a)}\n")

#output2 the follwing array: array([[[1., 2., 3.],
#                                    [1., 2., 3.],
#                                    [1., 2., 3.]],

#                                    [[1., 2., 3.],
#                                    [1., 2., 3.],
#                                    [1., 2., 3.]],

#                                    [[1., 2., 3.],
#                                    [1., 2., 3.],
#                                    [1., 2., 3.]]])

def output2(a):
    c = np.ones(3)
    d = a + c
    e = np.vstack((d,d,d))
    f = np.vstack((d,d,d))
    g = np.vstack((d,d,d))
    o2 = np.array((e,f,g)).reshape(3,3,3)
    return(o2)

print(f"output2 = {output2(a)}\n")

#output3 array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
#                [1., 1., 1., 1., 1., 1., 1., 1., 1.],
#                [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

def output3(b):
    v3 = np.hstack((b[0][0], b[0][1], b[0][2]))
    v4 = np.hstack((b[0][0], b[0][1], b[0][2]))
    v5 = np.hstack((b[0][0], b[0][1], b[0][2]))
    o3 = np.vstack((v3, v4, v5))
    return(o3)

print(f"output3 = {output3(b)}")

output1 = [0 0 0 1 1 1 2 2 2 0 1 2 0 1 2 0 1 2]

output2 = [[[1. 2. 3.]
  [1. 2. 3.]
  [1. 2. 3.]]

 [[1. 2. 3.]
  [1. 2. 3.]
  [1. 2. 3.]]

 [[1. 2. 3.]
  [1. 2. 3.]
  [1. 2. 3.]]]

output3 = [[1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]]
